---
title: "disagreement_reason_power_simulation"
author: "Hanna Schleihauf"
date: "5/24/2022"
output: pdf_document
---

## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls(all.names = TRUE))
library("tidyverse")
library("cowplot")
library("gghalves")
library("lme4")
library("kyotil") # we want to store info about convergence issues
```

## Generate Data
```{r, echo = FALSE}
set.seed(1)
n.dyads <- 180 # number of dyads
# range of age
min.age <- 5
max.age <- 9

n.n.per.dyad <- 2 # observations per dyad
n.condition <- 2 # number of conditions
n.per.condition <- 2 # observations per dyad and condition (between-dyad design)
dyad.id <- as.factor(paste("dyad", 1:n.dyads, sep = ".")) # creating a dyad ids

# expected performance levels
agreement.usa.5 <- 0.10 # <- reference level
agreement.china.5 <- 0.10
agreement.kenya.5 <- 0.05
agreement.usa.9 <- 0.20
agreement.china.9 <- 0.20
agreement.kenya.9 <- 0.15

disagreement.usa.5 <- 0.75
disagreement.china.5 <- 0.75
disagreement.kenya.5 <- 0.55
disagreement.usa.9 <- 0.85
disagreement.china.9 <- 0.85
disagreement.kenya.9 <- 0.85

start.data <- data.frame(dyad.id)

# duplicate rows according to the number obs. per dyad:
start.data <- start.data[rep(x = 1:nrow(start.data), times = n.n.per.dyad), ]
start.data <- as.data.frame(start.data)
names(start.data) <- "dyad.id"

# create between-dyad predictors
# predictor culture
start.data$condition <-
  as.factor(rep(x = c(".agreement", ".disagreement"), each = n.dyads /
    2))[as.numeric(start.data$dyad.id)]
start.data$culture <-
  as.factor(rep(x = c(".usa", ".china", ".kenya"), times = n.dyads /
    3))[as.numeric(start.data$dyad.id)]
start.data$culture <- relevel(start.data$culture, ref = ".usa")
# predictor sex
# start.data <- start.data[order(start.data$culture, start.data$dyad.id),]
start.data$gender <-
  as.factor(rep(x = c(".male", ".female", ".male", ".female"), each = n.dyads / 4))[as.numeric(start.data$dyad.id)]
# predictor age
start.data$age <-
  rep(x = runif(n = n.dyads, min = 4, max = 9))[as.numeric(start.data$dyad.id)]
# check whether it worked
ftable(condition ~ culture + gender, start.data) / 2

# create within-dyad predictor
# predictor trial number
start.data$trial <- ave(seq_along(start.data$dyad.id), start.data$dyad.id, FUN = seq_along)

# z-transformation of covariates
# z-transform age
start.data$z.age <- as.vector(scale(start.data$age))
start.data$z.trial <- as.vector(scale(as.numeric(start.data$trial)))

# dummy code factors and center them for random slopes
start.data$condition.disagreement <-
  as.numeric(start.data$condition == levels(start.data$condition)[2])
start.data$condition.disagreement.c <-
  as.numeric(start.data$condition.disagreement) -
  mean(as.numeric(start.data$condition.disagreement)) # centering
start.data$culture.china <-
  as.numeric(start.data$culture == levels(start.data$culture)[2])
start.data$culture.china.c <-
  start.data$culture.china - mean(start.data$culture.china) # centering
start.data$culture.kenya <-
  as.numeric(start.data$culture == levels(start.data$culture)[3])
start.data$culture.kenya.c <-
  start.data$culture.kenya - mean(start.data$culture.kenya) # centering

# dummy code and center gender to make the estimates unconditional of
# the reference category
start.data$gender.male <-
  as.numeric(start.data$gender == levels(start.data$gender)[2])
start.data$gender.male.c <-
  start.data$gender.male - mean(start.data$gender.male)

# checks:
# does each dyad have only one sex and age?
xx <- table(start.data$dyad.id, start.data$gender)
range(apply(X = xx > 0, MARGIN = 1, sum)) # should be 1 and 1

xx <- table(start.data$dyad.id, start.data$age)
range(apply(X = xx > 0, MARGIN = 1, sum)) # should be 1 and 1

xx <- table(start.data$dyad.id, start.data$condition)
range(apply(X = xx > 0, MARGIN = 1, sum))

xx <- table(start.data$dyad.id, start.data$trial)
range(apply(X = xx > 0, MARGIN = 1, sum))
```

## Calculate estimates/slopes based on our hypotheses
```{r, echo = FALSE}
# to calculate slope between two point one need to (y2-y2)/(x2-x1)
# reference levels
intercept <-
  mean(c(qlogis(agreement.usa.5), qlogis(agreement.usa.9)))

# slope of age is the effect of reason-giving with the other factors being on
# their reference levels (culture = usa, condition = agreement)
s.age <-
  (qlogis(agreement.usa.9) - qlogis(agreement.usa.5)) /
    (max(start.data$z.age) - min(start.data$z.age))

# slope of condition is the effect of reason-giving at age being at its average (0) or
# the average of the slopes of reason-giving against condition at age
# being at its minimum and maximum, respectively
s.condition.disagreement <-
  mean(c(
    (qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)),
    (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))
  ))

# slope of culture.china is zero because we expect the reason-giving rate for
# the US (reference level) and china to be the same
s.culture.china <-
  mean(c(
    (qlogis(agreement.china.9) - qlogis(agreement.usa.9)),
    (qlogis(agreement.china.5) - qlogis(agreement.usa.5))
  ))

# slope of culture.kenya
s.culture.kenya <-
  mean(c(
    (qlogis(agreement.kenya.9) - qlogis(agreement.usa.9)),
    (qlogis(agreement.kenya.5) - qlogis(agreement.usa.5))
  ))

# two-way interactions
# slope of age in the disagreement condition with culture at the reference level
# the slope for condition.disagreement:culture.age determines the effect of the interaction, i.e.,
# how much the effect of condition on reason-giving changes when age increases
# by one (or how much much the effect of age on reason-giving changes when
# condition increases by one, which is the same).
# We need to calculate:
# ((slope of age with condition being at its maximum(disagreement)  -
# slope of age with condition being at its minimum(agreement)) /
# (maximum of condition(disagreement) - min of condition(agreement))
s.age.condition.disagreement <-
  ((qlogis(disagreement.usa.9) - qlogis(disagreement.usa.5)) /
    (max(start.data$z.age) - min(start.data$z.age))) - # slope of age at condition being at its maximum (disagreement)
  ((qlogis(agreement.usa.9) - qlogis(agreement.usa.5)) /
    (max(start.data$z.age) - min(start.data$z.age))) # slope of age with #condition being at its minimum (agreement)

# since it also needs to work the other way around
s.condition.disagreement.age <-
  ((qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)) -
    (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))) /
    (max(start.data$z.age) - min(start.data$z.age))
# test whether both versions lead to the same result
round(s.age.condition.disagreement, 5) == round(s.condition.disagreement.age, 5)

# ((slope of age with culture being at its maximum(china)  -
# slope of age with culture being at its minimum(usa)) /
# (maximum of culture(china) - min of culture(usa))
s.age.culture.china <-
  (((qlogis(agreement.china.9) - qlogis(agreement.china.5)) /
    (max(start.data$z.age) - min(start.data$z.age))) -
    ((qlogis(agreement.usa.9) - qlogis(agreement.usa.5)) /
      (max(start.data$z.age) - min(start.data$z.age))))
# since it also needs to work the other way around
s.culture.china.age <-
  ((qlogis(agreement.china.9) - qlogis(agreement.usa.9)) -
    (qlogis(agreement.china.5) - qlogis(agreement.usa.5))) /
    (max(start.data$z.age) - min(start.data$z.age))
# test whether both versions lead to the same result
round(s.age.culture.china, 5) == round(s.culture.china.age, 5)

# ((slope of age with culture being at its maximum(kenya)  -
# slope of age with culture being at its minimum(usa)) /
# (maximum of culture(kenya) - min of culture(usa))
s.age.culture.kenya <-
  ((qlogis(agreement.kenya.9) - qlogis(agreement.kenya.5)) /
    (max(start.data$z.age) - min(start.data$z.age))) -
  ((qlogis(agreement.usa.9) - qlogis(agreement.usa.5)) /
    (max(start.data$z.age) - min(start.data$z.age)))
# since it also needs to work the other way around
s.culture.kenya.age <-
  ((qlogis(agreement.kenya.9) - qlogis(agreement.usa.9)) -
    (qlogis(agreement.kenya.5) - qlogis(agreement.usa.5))) /
    (max(start.data$z.age) - min(start.data$z.age))
# test whether both versions lead to the same result
round(s.culture.kenya.age, 5) == round(s.age.culture.kenya, 5)

# ((slope of condition with culture being at its maximum(china)  -
# slope of condition with culture being at its minimum(usa)) /
# (maximum of culture(china) - min of culture(usa))
s.culture.china.condition.disagreement <-
  mean(c(
    ((qlogis(disagreement.china.5) - qlogis(agreement.china.5)) -
      (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))),
    ((qlogis(disagreement.china.9) - qlogis(agreement.china.9)) -
      (qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)))
  ))
# since it also needs to work the other way around
s.condition.disagreement.culture.china <-
  mean(c(
    ((qlogis(disagreement.china.5) - qlogis(disagreement.usa.5)) -
      (qlogis(agreement.china.5) - qlogis(agreement.usa.5))),
    ((qlogis(disagreement.china.9) - qlogis(disagreement.usa.9)) -
      (qlogis(agreement.china.9) - qlogis(agreement.usa.9)))
  ))
# test whether both versions lead to the same result
round(s.culture.china.condition.disagreement, 5) == round(s.condition.disagreement.culture.china, 5)

# ((slope of condition with culture being at its maximum(kenya)  -
# slope of condition with culture being at its minimum(usa)) /
# (maximum of culture(kenya) - min of culture(usa))
s.culture.kenya.condition.disagreement <-
  mean(c(
    ((qlogis(disagreement.kenya.5) - qlogis(agreement.kenya.5)) -
      (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))),
    ((qlogis(disagreement.kenya.9) - qlogis(agreement.kenya.9)) -
      (qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)))
  ))
# since it also needs to work the other way around
s.condition.disagreement.culture.kenya <-
  mean(c(
    ((qlogis(disagreement.kenya.5) - qlogis(disagreement.usa.5)) -
      (qlogis(agreement.kenya.5) - qlogis(agreement.usa.5))),
    ((qlogis(disagreement.kenya.9) - qlogis(disagreement.usa.9)) -
      (qlogis(agreement.kenya.9) - qlogis(agreement.usa.9)))
  ))
# test whether both versions lead to the same result
round(s.culture.kenya.condition.disagreement, 5) == round(s.condition.disagreement.culture.kenya, 5)

# three way-interactions
s.condition.disagreement.culture.china.age <-
  # slope for condition at max age for china
  ((((qlogis(disagreement.china.9) - qlogis(agreement.china.9)) -
    # slope for condition at min age for china
    (qlogis(disagreement.china.5) - qlogis(agreement.china.5))) /
    (max(start.data$z.age) - min(start.data$z.age))) -
    # slope for condition at max age for us
    (((qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)) -
      # slope for condition at min age for us
      (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))) /
      (max(start.data$z.age) - min(start.data$z.age))))

s.condition.disagreement.culture.kenya.age <-
  # slope for condition at max age for kenya
  ((((qlogis(disagreement.kenya.9) - qlogis(agreement.kenya.9)) -
    # slope for condition at min age for kenya
    (qlogis(disagreement.kenya.5) - qlogis(agreement.kenya.5))) /
    (max(start.data$z.age) - min(start.data$z.age))) -
    # slope for condition at max age for us
    (((qlogis(disagreement.usa.9) - qlogis(agreement.usa.9)) -
      # slope for condition at min age for us
      (qlogis(disagreement.usa.5) - qlogis(agreement.usa.5))) /
      (max(start.data$z.age) - min(start.data$z.age))))
```

## Define random effects and slopes 
```{r, echo = FALSE}
n.simus <- 50 # small number for testing
# random effect
# educated guess of what the random effect could be (based on the qlogis of the reference level performance)
tiny.re <- abs(qlogis(agreement.usa.5) / 8)
moderate.re <- abs(qlogis(agreement.usa.5) / 4)
strong.re <- abs(qlogis(agreement.usa.5) / 2)
extrem.re <- abs(qlogis(agreement.usa.5) * 1)
r.effects <- c(tiny.re, moderate.re, strong.re)

# random slope for trial
r.slope.trial <- 0.1
```

#Prepare simulation
```{r, echo = FALSE}
# create object to store the simulation parameters and results:
all.res <-
  data.frame(expand.grid(
    r.effect = r.effects,
    r.slope.trial = r.slope.trial, simu = 1:n.simus
  ))


# add columns for estimates
all.res$icpt <- NA
all.res$z.age <- NA
all.res$condition.disagreement <- NA
all.res$culture.china <- NA
all.res$culture.kenya <- NA
all.res$gender.male.c <- NA
all.res$z.trial <- NA
all.res$z.age.condition.disagreement <- NA
all.res$z.age.culture.china <- NA
all.res$z.age.culture.kenya <- NA
all.res$condition.disagreement.culture.china <- NA
all.res$condition.disagreement.culture.kenya <- NA
all.res$z.age.condition.disagreement.culture.china <- NA
all.res$z.age.condition.disagreement.culture.kenya <- NA
# add columns for re.sd and warnings for full model and null model
all.res$re.sd <- NA
all.res$warns.full <- NA
all.res$warns.null <- NA
# add columns for likelihood ratio test results (p-values)
all.res$full.null.p <- NA
all.res$lrt.p.condition <- NA
all.res$lrt.p.z.age <- NA
all.res$lrt.p.culture <- NA
all.res$lrt.p.gender.male.c <- NA
all.res$lrt.p.z.trial <- NA
all.res$lrt.p.z.age.condition <- NA
all.res$lrt.p.condition.culture <- NA
all.res$lrt.p.z.age.culture <- NA
all.res$lrt.p.z.age.condition.culture <- NA



# create vector with coefficients
coefs <- c(
  "(Intercept)" = intercept,
  "z.age" = s.age,
  "condition.disagreement" = s.condition.disagreement,
  "culture.china" = s.culture.china,
  "culture.kenya" = s.culture.kenya,
  "gender.male.c" = 0,
  "z.trial" = 0,
  "z.age:condition.disagreement" =  s.condition.disagreement.age,
  "z.age:culture.china" = s.culture.china.age,
  "z.age:culture.kenya" = s.culture.kenya.age,
  "condition.disagreement:culture.china" = s.condition.disagreement.culture.china,
  "condition.disagreement:culture.kenya" = s.condition.disagreement.culture.kenya,
  "z.age:condition.disagreement:culture.china" = s.condition.disagreement.culture.china.age,
  "z.age:condition.disagreement:culture.kenya" = s.condition.disagreement.culture.kenya.age
)
```

#start simulation
```{r, echo = FALSE}
xdata <- start.data # change start.data to xdata

str(xdata)
# create model matrix
m.mat <- model.matrix(object = ~ z.age * condition * culture + gender.male.c + z.trial, data = xdata) # create model matrix
# create LP wrt fixed effects
LP <- m.mat[, names(coefs)] %*% coefs

# define control structure to make convergence more likely:
contr <- glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 10000))

# run simulation
for (i in 1:nrow(all.res)) {
  set.seed(i) # allows to later replicate individual simulations
  # add random effect to linear predictor:
  LP <- LP + rnorm(n = n.dyads, sd = all.res[i, "r.effect"])[as.numeric(xdata$dyad.id)] +
    rnorm(n = n.dyads, sd = all.res[i, "r.slope.trial"])[as.numeric(xdata$dyad.id)] * xdata$z.trial
  # generate response:
  xdata$reasons <- rbinom(n = nrow(xdata), size = 1, prob = exp(LP) / (1 + exp(LP)))

  # fit full model:
  full <- keepWarnings(glmer(reasons ~
  (z.age + condition + culture)^3 + gender.male.c + z.trial +
    (1 + (z.trial) || dyad.id),
  data = xdata, family = binomial, control = contr
  ))

  # fit null model:
  null <- keepWarnings(glmer(reasons ~ 1 +
    (1 + (z.trial) || dyad.id),
  data = xdata, family = binomial, control = contr
  ))
  # fit reduced model with two-way interactions:
  red1 <- keepWarnings(glmer(reasons ~
  (z.age + condition + culture)^2 + gender.male.c + z.trial +
    (1 + (z.trial) || dyad.id),
  data = xdata, family = binomial, control = contr
  ))
  # fit reduced model with only main effects:
  red2 <- keepWarnings(glmer(reasons ~
  (z.age + condition + culture) + gender.male.c + z.trial +
    (1 + (z.trial) || dyad.id),
  data = xdata, family = binomial, control = contr
  ))

  # store results:
  all.res[i, c("icpt", "z.age", "condition.disagreement", "culture.china", "culture.kenya", "gender.male.c", "z.trial", "z.age.condition.disagreement", "z.age.culture.china", "z.age.culture.kenya", "condition.disagreement.culture.china", "condition.disagreement.culture.kenya", "z.age.condition.disagreement.culture.china", "z.age.condition.disagreement.culture.kenya")] <- fixef(full$value)

  all.res[i, "re.sd"] <- as.data.frame(summary(full$value)$varcor)[1, "sdcor"]
  all.res[i, "warns.full"] <- nchar(paste(full$warnings, collapse = ""))
  all.res[i, "warns.null"] <- nchar(paste(null$warnings, collapse = ""))
  all.res[i, "full.null.p"] <-
    as.data.frame(anova(null$value, full$value, test = "Chisq"))[2, "Pr(>Chisq)"]
  all.res[i, "lrt.p.z.age.condition.culture"] <-
    as.data.frame(drop1(full$value, test = "Chisq"))["z.age:condition:culture", "Pr(Chi)"]

  xx <- drop1(red1$value, test = "Chisq")
  all.res[i, "lrt.p.z.age.culture"] <- as.data.frame(xx)["z.age:culture", "Pr(Chi)"]
  all.res[i, "lrt.p.condition.culture"] <- as.data.frame(xx)["condition:culture", "Pr(Chi)"]
  all.res[i, "lrt.p.z.age.condition"] <- as.data.frame(xx)["z.age:condition", "Pr(Chi)"]

  xx <- drop1(red2$value, test = "Chisq")
  all.res[i, "lrt.p.condition"] <- as.data.frame(xx)["condition", "Pr(Chi)"]
  all.res[i, "lrt.p.culture"] <- as.data.frame(xx)["culture", "Pr(Chi)"]
  all.res[i, "lrt.p.z.age"] <- as.data.frame(xx)["z.age", "Pr(Chi)"]
  all.res[i, "lrt.p.z.trial"] <- as.data.frame(xx)["z.trial", "Pr(Chi)"]
  all.res[i, "lrt.p.gender.male.c"] <- as.data.frame(xx)["gender.male.c", "Pr(Chi)"]

  print(i)
}

save.image("Disagreement_Reason_Power_Simulation.RData")
load("Disagreement_Reason_Power_Simulation.RData")
```
## Evaluation of results 
```{r, echo = FALSE}
# full model
all.res1 <- all.res
tapply(
  X = all.res1[, "warns.full"] > 0, INDEX = all.res1[, c("r.effect")],
  FUN = sum
)

sum(all.res1[, "warns.full"] > 0)

# null model
# null model:
tapply(
  X = all.res1[, "warns.null"] > 0, INDEX = all.res1[, c("r.effect")],
  FUN = sum
)

all.res1

options(scipen = 9999)
```

## Only models that converged are evaluated from here on:  

```{r include=FALSE}
all.res1 <- subset(all.res, warns.full == 0)

str(all.res)
```

### How many models converged, have a significant full-null model comparison, and a significant LRT of condition?  
```{r echo=FALSE}

lrt.data2 <- all.res1 %>%
  filter(full.null.p < 0.05) %>%
  group_by(r.effect) %>%
  summarise(
    proportion.lrt.z.age.condition = length(lrt.p.z.age.condition[lrt.p.z.age.condition < 0.05]) / n.simus,
    proportion.lrt.z.age.condition.culture = length(lrt.p.z.age.condition.culture[lrt.p.z.age.condition.culture < 0.05]) / n.simus,
    proportion.lrt.z.culture.condition = length(lrt.p.condition.culture[lrt.p.condition.culture < 0.05]) / n.simus,
    proportion.lrt.condition = length(lrt.p.condition[lrt.p.condition <= 0.05]) / n.simus
  )
lrt.data2

ftable(xdata$reasons ~ xdata$condition + xdata$culture)

all.res$lrt.p.z.age.condition[all.res$lrt.p.z.age.condition < 0.05] / n.simus
(all.res$lrt.p.z.age.condition < 0.05) / n.simus
```
